version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: blockchain_db
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5432:5432"

  go_service:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: yourpassword
      DB_NAME: blockchain_db
      RPC_ENDPOINT: https://data-seed-prebsc-2-s3.binance.org:8545/
    ports:
      - "8080:8080"
    entrypoint: go run main.go

volumes:
  db-data:
